# Generated by Django 3.2.3 on 2021-06-03 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0002_auto_20210603_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='rating',
        ),
        migrations.AddField(
            model_name='hotels',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_hotels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotelservice', to='hotels.hotels'),
        ),
    ]
