# Generated by Django 3.2.3 on 2021-06-08 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20210603_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numberofrooms', models.PositiveSmallIntegerField(default=1)),
                ('imgroom', models.ImageField(blank=True, null=True, upload_to='imagesroom/%Y/%m/%d', verbose_name=' Изображение комнаты')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotelroom', to='hotels.hotels')),
            ],
        ),
    ]
