# Generated by Django 3.2.3 on 2021-06-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Numberofrooms',
            new_name='Numberofseats',
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
