# Generated by Django 3.2.3 on 2021-06-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20210608_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Numberofseats',
            new_name='numberofseats',
        ),
    ]
