# Generated by Django 3.2.3 on 2021-06-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
