# Generated by Django 3.2.3 on 2021-06-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_remove_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.AddField(
            model_name='room',
            name='ss',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
