# Generated by Django 3.2.3 on 2021-06-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_auto_20210617_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='ss',
            new_name='description',
        ),
    ]
