# Generated by Django 3.2.3 on 2021-06-28 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0010_rename_ss_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_hotels', to=settings.AUTH_USER_MODEL),
        ),
    ]
