# Generated by Django 3.2.3 on 2021-05-20 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_room', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room_feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.CharField(choices=[(1, 'одноместный'), (2, 'двухместный'), (3, 'трехместный'), ('L', 'Люкс')], max_length=1)),
                ('occupation', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
    ]
